name: cw_decred
description: A new Flutter package project.
version: 0.0.1
publish_to: none
author: Cake Wallet
homepage: https://cakewallet.com

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.11
  http: ^0.13.4
  mobx: ^2.0.7+4
  flutter_mobx: ^2.0.6+1
  intl: ^0.17.0
  cw_core:
    path: ../cw_core
  bitcoin_flutter:
    git:
      url: https://github.com/cake-tech/bitcoin_flutter.git
      ref: cake-update-v2
  rxdart: ^0.27.5
  unorm_dart: ^0.2.0
  cryptography: ^2.0.5
  encrypt: ^5.0.1
  meta: ^1.2.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  build_resolvers: ^2.0.9
  mobx_codegen: ^2.0.7
  hive_generator: ^1.1.3
